# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
      - valgrind
      
r_check_args: travis_wait 30 '--use-valgrind --as-cran'

env:
  - VALGRIND_OPTS = '--leak-check=full --track-origins=yes'