# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages: 
      - valgrind

#r_build_args: "--no-build-vignettes"
#r_check_args: "--as-cran --run-dontrun --use-valgrind"
env:
  - VALGRIND_OPTS="--leak-check=full --track-origins=yes"
  
script: 
  - |
    travis_wait 42 R CMD build . --no-build-vignettes
    travis_wait 59 R CMD check MLZ*tar.gz --as-cran --run-dontrun --use-valgrind
    