# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

install: travis_wait 30

addons:
  apt:
    packages:
      - valgrind
      
r_check_args: '--use-valgrind'

env:
  - VALGRIND_OPTS = '--leak-check=full --track-origins=yes'