# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MLnegLL <- function(stpar, Lbar, ss, LH, Lc, nbreaks, spCont) {
    .Call('MLZ_MLnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, spCont)
}

MLprofile <- function(Z, yearZ, Lbar, ss, LH, Lc, nbreaks, spCont) {
    .Call('MLZ_MLprofile', PACKAGE = 'MLZ', Z, yearZ, Lbar, ss, LH, Lc, nbreaks, spCont)
}

MLpred <- function(stpar, Lbar, ss, LH, Lc, nbreaks, spCont) {
    .Call('MLZ_MLpred', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, spCont)
}

MLfullnegLL <- function(stpar, Lbar, ss, LH, Lc, nbreaks, spCont) {
    .Call('MLZ_MLfullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, spCont)
}

MLe <- function(stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar) {
    .Call('MLZ_MLe', PACKAGE = 'MLZ', stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar)
}

MLepred <- function(stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar) {
    .Call('MLZ_MLepred', PACKAGE = 'MLZ', stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar)
}

MLefullnegLL <- function(stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar) {
    .Call('MLZ_MLefullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar)
}

MLefixM <- function(stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar) {
    .Call('MLZ_MLefixM', PACKAGE = 'MLZ', stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar)
}

MLefixMfullnegLL <- function(stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar) {
    .Call('MLZ_MLefixMfullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, eff, LH, Lc, eff_init, n_age, n_season, obs_season, timing, logpar)
}

MLeqnegLL <- function(Z, Lbar, ss, LH, Lc, spCont) {
    .Call('MLZ_MLeqnegLL', PACKAGE = 'MLZ', Z, Lbar, ss, LH, Lc, spCont)
}

MLeqpred <- function(Z, Lbar, ss, LH, Lc, spCont) {
    .Call('MLZ_MLeqpred', PACKAGE = 'MLZ', Z, Lbar, ss, LH, Lc, spCont)
}

MLeqfullnegLL <- function(stpar, Lbar, ss, LH, Lc, spCont) {
    .Call('MLZ_MLeqfullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, spCont)
}

SSM_MSM1_negLL <- function(stpar, Lbar, ss, LH, Lc, nbreaks, isMSM1, spCont) {
    .Call('MLZ_SSM_MSM1_negLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, isMSM1, spCont)
}

SSM_MSM1_profile <- function(stpar, year, Lbar, ss, LH, Lc, nbreaks, spCont) {
    .Call('MLZ_SSM_MSM1_profile', PACKAGE = 'MLZ', stpar, year, Lbar, ss, LH, Lc, nbreaks, spCont)
}

SSM_MSM1_pred <- function(stpar, Lbar, ss, LH, Lc, nbreaks, isMSM1, spCont) {
    .Call('MLZ_SSM_MSM1_pred', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, isMSM1, spCont)
}

SSM_MSM1_fullnegLL <- function(stpar, Lbar, ss, LH, Lc, nbreaks, isMSM1, spCont) {
    .Call('MLZ_SSM_MSM1_fullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, isMSM1, spCont)
}

MSM23_negLL <- function(stpar, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont) {
    .Call('MLZ_MSM23_negLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont)
}

MSM23_profile <- function(stpar, year, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont) {
    .Call('MLZ_MSM23_profile', PACKAGE = 'MLZ', stpar, year, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont)
}

MSM23_pred <- function(stpar, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont) {
    .Call('MLZ_MSM23_pred', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont)
}

MSM23_fullnegLL <- function(stpar, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont) {
    .Call('MLZ_MSM23_fullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, LH, Lc, nbreaks, isMSM3, spCont)
}

MLNPUEnegLL <- function(stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLNPUEnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLNPUEprofile <- function(Z, yearZ, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLNPUEprofile', PACKAGE = 'MLZ', Z, yearZ, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLNPUEpred <- function(stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLNPUEpred', PACKAGE = 'MLZ', stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLNPUEfullnegLL <- function(stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLNPUEfullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLWPUEnegLL <- function(stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLWPUEnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLWPUEprofile <- function(Z, yearZ, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLWPUEprofile', PACKAGE = 'MLZ', Z, yearZ, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLWPUEpred <- function(stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLWPUEpred', PACKAGE = 'MLZ', stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

MLWPUEfullnegLL <- function(stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont) {
    .Call('MLZ_MLWPUEfullnegLL', PACKAGE = 'MLZ', stpar, Lbar, ss, CPUE, LH, Lc, nbreaks, loglikeCPUE, spCont)
}

